import java.math.BigInteger;
import java.util.ArrayList;

/**
 * Finds the number of distinct terms in the sequence generated by a^b for 
 * 2 <= a <= 100 and 2 <= b <= 100
 * 
 * @author derek.steinke
 * 
 */

public class P29 {

	public static void main(String[] args) {
		long start = System.nanoTime();
		ArrayList<BigInteger> distinctPowers = new ArrayList<>();
		
		//A simple brute force loop
		for (int i = 2; i <= 100; i++) {
			for (int k = 2; k <= 100; k++) {
				BigInteger power = BigInteger.valueOf(i);
				power.pow(k);
				if (!distinctPowers.contains(power)) {
					distinctPowers.add(power);
				}
			}
		}
		System.out.println(distinctPowers.size());
		System.out.println("Done in " + (double) (System.nanoTime() - start)
				/ 1000000000 + " seconds.");

	}
}
